### Listar todos os usuários
GET http://localhost:8000/api/v1/users
Accept: application/json

### Criar usuário
POST http://localhost:8000/api/v1/users
Content-Type: application/json
Accept: application/json

{
  "name": "Davi",
  "email": "davi@email.com",
  "password": "123456"
}

### Mostrar usuário por ID
GET http://localhost:8000/api/v1/users/1
Accept: application/json

### Atualizar usuário
PUT http://localhost:8000/api/v1/users/1
Content-Type: application/json
Accept: application/json

{
  "name": "Davi Atualizado"
}

### Deletar usuário
DELETE http://localhost:8000/api/v1/users/1
Accept: application/json
